### ISSUE TITLE
Why not integrate SequentialChain in LangFlow

### ISSUE THREAD

**Issue by JefferyLJF1129** [logspace-ai/langflow#1165]
Hi, I'm wondering why SequentialChain is not integrated into LangFlow? I believe this is an important component to enhance the scalability of LangFlow projects. I would like to know if there are any related technical issues or considerations in terms of product design.

**Comment by yamonkjd** [comment]
I think Langflow's contributors are focusing on UI mapping. It seems that progress is being made in the direction of opening up flexibility so that users can implement the elements they need as custom components.

Like you, we also use our own implementation of prompt routing using LLM, which has recently been redesigned in LangChain.

https://python.langchain.com/docs/modules/chains/foundational/sequential_chains

This LangChain component's specifications have also recently changed, and it is thought to be difficult for LangFlow's contributors to directly respond to these changes.

Accordingly, Langflow users are encouraged to participate in implementing custom components, creating pull requests, and sharing them with each other.
