### ISSUE TITLE
How to access input message in custom component?

### ISSUE THREAD

**Issue by Elsayed91** [logspace-ai/langflow#1166]
Hi

The first component in my flow is a custom component. Now I want to pass the input message to it in the python code panel, but am unsure how to do that. I am able to create a solution by using tweaks, but if it is possible to use the `inputs": {"input": "message"}` that would be much better.

current implementation
```
  http://127.0.0.1:7860/api/v1/process/4d43b9b8-7808-4e58-91b6-69d3fab5402a \
  -H 'Content-Type: application/json'\
  -d '{"inputs": {"input": "message"}, "tweaks": {
  "CustomComponent-zM1mh": {
    "inputs": "whats up?"
  }
}}'
```

is it possible?

**Comment by yamonkjd** [comment]
```
def wrapped_run_flow(message: str, tweaks: Optional[dict] = None) -> dict:
    """
    Wrapper function to run the flow with a given message and optional tweaks.

    :param message: The message to send to the flow
    :param tweaks: Optional tweaks to customize the flow
    :return: The JSON response from the flow
    """
    inputs = {"text": message}
    return run_flow(inputs, flow_id=FLOW_ID, tweaks=tweaks)

def main():
    user_session_id = int(input("Enter the session ID: "))
    TWEAKS["MongoDBChatMessageHistory-5RXNx"]["session_id"] = user_session_id

    while True:
        user_input = input("You: ")  # Get user input
        response = wrapped_run_flow(user_input, tweaks=TWEAKS)
        assistant_response = response["result"]["text"]

        print(f"AI: {assistant_response}")

if __name__ == "__main__":
    main()
    
    
```

I am testing the flow with Python code in this way. (Put the relevant source at the bottom of Langflow's Python code and remove the simple call part)

As a result of checking the related parts of Langflow, when executing a flow, it looks for a component with an input key of "input" and searches for that object as the start of the flow, so this implementation seems to be the best for now. As you said, if it is modified so that it can be transmitted that way when accessed from a Python endpoint, its usability will increase. (For input of images, audio files, etc.)
