### ISSUE TITLE
Bedrock is missing from the components of LLM section.

### ISSUE THREAD

**Issue by nsy0328** [logspace-ai/langflow#1483]
**Describe the bug**

Amazon Bedrock is not selectable from the LLMs.
I installed in order from v0.6.8 and confirmed that Amazon Bedrock is not displayed between versions v0.6.6 and v0.6.5.
I can confirm that the files for Amazon Bedrock exist for v0.6.6 and later, but is it not supported for v0.6.6 and later?

![Screenshot 2024-02-29 at 17 44 47](https://github.com/logspace-ai/langflow/assets/53632932/8ea6baf6-f619-49a7-b654-df1305d9c175)

**Comment by msalehie-qual** [comment]
I have the same issue. Bedrock doesn't even show up in the left panel. I noticed it's missing from the config.yaml in this path:
`/Users/msalehie/opt/anaconda3/envs/py311/lib/python3.11/site-packages/langflow `

I added this line under llm in the config file:
```
llms:
  Bedrock:
    documentation: "https://python.langchain.com/docs/integrations/llms/bedrock"

```
and ran again the langflow. Now I can see the Bedrock under LLM. But the problem is that I don't see the fields for credentials and endpoint URL in the UI. I expect to see these like the openAI component. 
![Screenshot 2024-02-29 at 7 05 18 PM](https://github.com/logspace-ai/langflow/assets/161791813/fbcc4152-70fb-4f23-b36e-738600f3f3c4)

**Comment by msalehie-qual** [comment]
I actually managed to build a flow to call Bedrock using the "custom component". I copied the code from AmazonBedrock.py into the custom component, and saw all the fields. The flow ran without any problem.

**Comment by nsy0328** [comment]
Thank you, @msalehie-qual, for your response.
I can use Amazon Bedrock from "Custom Component"!

---

For those who encounter this issue after me, the procedure would be as follows:
Select Custom Component 
![Screenshot 2024-03-01 at 15 53 19](https://github.com/logspace-ai/langflow/assets/53632932/3b0f6b6f-d1d3-4565-a7cd-8ee2f6672a6a)

Edit Code → paste the code (AmazonBedrock.py)
![Screenshot 2024-03-01 at 16 00 12](https://github.com/logspace-ai/langflow/assets/53632932/ddc60974-d80c-4353-ae9a-f9ac3de425ff)

Upon returning to the flow page, Amazon Bedrock should now be available.
![Screenshot 2024-03-01 at 16 01 00](https://github.com/logspace-ai/langflow/assets/53632932/441a824d-8117-4d03-908f-16090dbfb859)
