### ISSUE TITLE
Number of requested results 4 cannot be greater than number of elements in index 3  

### ISSUE THREAD

**Issue by lgertel** [logspace-ai/langflow#189]
**Describe the bug**
ERROR - Error: Number of requested results 4 cannot be greater than number of elements in index 3  

**Browser and Version**
 - Chrome
 - 112.0.5615.137

**Screenshots**
[image](https://media.discordapp.net/attachments/1087039170029047892/1100188941627428864/CleanShot_2023-04-24_at_19.37.51.png?width=1150&height=702)

**Comment by ogabrielluiz** [comment]
This was fixed in 76162a9ffa8314013fadb04217e09a688a635e97

It happens because what you are trying to load is not generating at least 4 documents which is the default number of retrieved documents by ChromaDB.

If you fix the split it could help (maybe the separator or the chunk size). 

We are working on better tooling for debugging this kind of things.

**Comment by lgertel** [comment]
Is this one already available via pip or should I custom build it?
Thanks for the answer!

**Comment by ogabrielluiz** [comment]
We'll release a new version today with many fixes and some new features.
