### ISSUE TITLE
BaseLLM bug

### ISSUE THREAD

**Issue by XavierRex** [logspace-ai/langflow#47]
![bug](https://user-images.githubusercontent.com/98437003/226207832-70532618-cc6f-4628-9537-498bfd580a32.png)

I can't connect the model to any tool or LLMMathChain. OpenAI model input type is str. (0.0.40 version on windows)

**Comment by ogabrielluiz** [comment]
Hey! 
We'll look into that ASAP. 

@ibiscp do you know what could be causing this? I tested it here and it happened to me too.

I ran `pip install langflow -U`and `langflow` put the OpenAI node and the PAL-MATH node and I can't connect them to each other.

Maybe the output to OpenAI shouldn't be str.

**Comment by ibiscp** [comment]
I'll debug that.

**Comment by ScripterSugar** [comment]
In frontend/src/CustomNodes/GenericNode.js L84
```
id={data.type + "|" + data.id + data.node.base_classes.map((b) => ("|" + b))}
```
This line is wrong because it produces id in the form like this `OpenAI|dndnode_26|BaseOpenAI,|BaseLLM,|BaseLanguageModel`
You can see the trailing commas making isValidConnection to return false-negatives on valid connections.
We also need to fix hard-coded "type:str" notation on ParameterComponent. I'd like to also find a way to actually use type parameter rather than just parse handle's id field, but I'm not sure that's doable as this is my first time using reactflow library.

May I open PR from my fork to address this issue or someone's already working on it?

**Comment by ogabrielluiz** [comment]
Thanks for the help! I'll test it out now.
@anovazzi1, what do you think about the hard-coded "type:str"? Could you give us more insight into that?

**Comment by ScripterSugar** [comment]
I fixed the tooltip part, but changing `type={'str'}` part will trigger some side effects within the handling code so I decided not to touch that until I'm certain about its behavior 😄

**Comment by ogabrielluiz** [comment]
Ok. I'll open a discussion based on your comment so we can maybe think of a better solution.
