### ISSUE TITLE
installing on gcp vm , error showed irewall rules must be of the form PROTOCOL[:PORT[-PORT]]; received [:tcp:3389].

### ISSUE THREAD

**Issue by jianglanCao** [logspace-ai/langflow#474]
ERROR: (gcloud.compute.firewall-rules.create) Firewall rules must be of the form PROTOCOL[:PORT[-PORT]]; received [:tcp:3389].

WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
Created [https://www.googleapis.com/compute/v1/projects/chatpdf-pro/zones/us-central1-a/instances/langflow-dev].
WARNING: Some requests generated warnings:
 - Disk size: '100 GB' is larger than image size: '10 GB'. You might need to resize the root repartition manually if the operating system does not support automatic resizing. See https://cloud.google.com/compute/docs/disks/add-persistent-disk#resize_pd for details.

**Comment by rajathooda** [comment]
same issue for me

**Comment by dolo-dolo** [comment]
Same issue.

**Comment by nanakusa68** [comment]
If you change scripts/deploy_langflow_gcp.sh to remove the unnecessary colon on line 38, the error will not occur.

Before: gcloud compute firewall-rules create allow-iap --network $VPC_NAME --allow tcp:80,tcp:443,tcp:22,:tcp:3389 --source-ranges 35.235.240.0/ 20 --direction INGRESS
After: gcloud compute firewall-rules create allow-iap --network $VPC_NAME --allow tcp:80,tcp:443,tcp:22,tcp:3389 --source-ranges 35.235.240.0/ 20 --direction INGRESS

Still, I have not been able to use langflow with GCP yet due to other problems.
