### ISSUE TITLE
Unsupported chat history format: <class str>

### ISSUE THREAD

**Issue by jon-chuang** [logspace-ai/langflow#532]
**Describe the bug**
Unsupported chat history format: `<class str>` upon second message. 

**Browser and Version**
Chrome

**To Reproduce**

**Screenshots**
see the following flow: 
![image](https://github.com/logspace-ai/langflow/assets/9093549/65664edc-ebd2-45ae-8d49-658dfe83e242)

`Does not work with ConversationalBuffer either`

**Additional context**

**Comment by jon-chuang** [comment]
Works with `RetrievalQA`:
![image](https://github.com/logspace-ai/langflow/assets/9093549/710ec195-ac7c-45d0-a9ef-037576cd2a3f)

Not sure why `ConversationalRetrieverChain` does not work. I consider this a bug.

**Comment by ianbbqzy** [comment]
Running into the same issue. Passing in `return_source_documents=True` also fails.

**Comment by ogabrielluiz** [comment]
Hey @jon-chuang 
To fix that issue, switch `return_messages` on the Memory component to On.

**Comment by ogabrielluiz** [comment]
This could be considered a LangChain bug. From what I've seen in the code there's still a mismatch of parameters and checks related to memories. 

@ianbbqzy about the `return_source_documents` this still puzzles me, because if I use it exactly as it is in their documentation, I still can't make it work. Either way, you can try setting the `output_key` of the memory component to `answer` maybe that will make it work. 

We do not support returning documents as of yet but soon we will.
