### ISSUE TITLE
Path based routing support for langflow

### ISSUE THREAD

**Issue by boarder7395** [logspace-ai/langflow#794]
**Describe the bug**
Using SCRIPT_NAME to change the base url prefix of the langflow service does not work. 

**To Reproduce**
Change SCRIPT_NAME env variable and launch UI.

**Additional context**
I'd like to host langflow on our Kubernetes cluster which implements a service mesh (istio). We'd like to keep all inbound traffic behind https://example.com and use path based routing for different applications. We currently run kubeflow on the cluster so each namespace is a different project. Then each project's langflow server would be available at "https://example.com/<namespace>/langflow/".

**Comment by Fulladorn** [comment]
+1

I have a similar use case of using this within AWS Sagemaker where the base URL looks something like `https://{domain-id}.{region}.sagemaker.aws/jupyter/default/proxy/7860`. However, when I try to access langchain, it references default assets at the base URL of `https://{domain-id}.{region}.sagemaker.aws` instead of `https://{domain-id}.{region}.sagemaker.aws/jupyter/default/proxy/7860/assets`
