### ISSUE TITLE
why the new version the agent cant connect with chain？

### ISSUE THREAD

**Issue by Sallery-X** [logspace-ai/langflow#905]

**Comment by Sallery-X** [comment]
like this 
![09d66993-69dc-45f5-a36e-abd7ba3b0cc6](https://github.com/logspace-ai/langflow/assets/45587738/d289942c-0c52-42c8-a8c9-6c77207edde6)

**Comment by yamonkjd** [comment]
After some consideration, I've found that in the case of agents pre-implemented in LangFlow, they need to be initialized and passed to the AgentExecutor. During this process, the parameters include an LLM chain, which seems to cause issues when executing the flow. Due to this, I am also in the process of creating my own agents.
